ServiceProvider/Controllers/BanController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ServiceProvider.Database;
using ServiceProvider.Helpers;
using ServiceProvider.Models;

namespace ServiceProvider.Controllers
{
	public class BanController : Controller
	{
		public const string UnauthorizedView = "../User/Unauthorized";

		IWebHostEnvironment _webHostEnvironment;
		private readonly ILogger<BanController> _logger;
		private AppDbContext _context;

		public BanController(IWebHostEnvironment webHostEnvironment, ILogger<BanController> logger, AppDbContext context)
		{
			_webHostEnvironment = webHostEnvironment;
			_logger = logger;
			_context = context;
		}

		[HttpGet]
		public IActionResult Index()
		{
			if (!SessionHelper.IsLoggedIn(this, true))
				return View(UnauthorizedView);

			return View(_context.BannedUsers
				.Include(x => x.User)
				.OrderByDescending(x => x.BanTime)
				.ToList()
				);
		}

		[HttpGet]
		public IActionResult Add(int? id)
		{
			if (!SessionHelper.IsLoggedIn(this, true))
				return View(UnauthorizedView);

			return View(id != null ?
				new BannedUser { UserId = id.Value }
				: null);
		}

		[HttpPost]
		public IActionResult PostAdd(BannedUser ban)
		{
			if (!SessionHelper.IsLoggedIn(this, true))
				return View(UnauthorizedView);

			if (ModelState.IsValid)
			{
				if (_context.Users.FirstOrDefault(x => x.Id == ban.UserId) != null)
				{
					if (_context.BannedUsers.FirstOrDefault(x => x.UserId ==  ban.UserId) == null)
					{
						ban.BanTime = DateTime.Now;

						_context.BannedUsers.Add(ban);
						_context.SaveChanges();

						return RedirectToAction("Index");
					}
					else
						ModelState.AddModelError(string.Empty, "This user is already banned.");
				}
				else
					ModelState.AddModelError(string.Empty, "User could not be found.");
			}
			return View("Add", ban);
		}

		[HttpGet]
		public IActionResult Delete(int id)
		{
			if (!SessionHelper.IsLoggedIn(this, true))
				return View(UnauthorizedView);

			return View(_context.BannedUsers
				.Where(x => x.Id == id)
				.Include(x => x.User)
				.FirstOrDefault()
				);
		}

		[HttpPost]
		public IActionResult PostDelete(int id)
		{
			if (!SessionHelper.IsLoggedIn(this, true))
				return View(UnauthorizedView);

			if (id != null && id > 0)
			{
				BannedUser? ban = _context.BannedUsers.FirstOrDefault(x => x.Id == id);
				if (ban != null)
				{
					_context.BannedUsers.Remove(ban);
					_context.SaveChanges();

					return RedirectToAction("Index");
				}
			}
			return View("Delete", null);
		}
	}
}

ServiceProvider/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using ServiceProvider.Database;
using ServiceProvider.Models;
using Newtonsoft.Json.Converters;
using ServiceProvider.Helpers;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System.Text.RegularExpressions;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.FileProviders;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceProvider.Controllers
{
	public class UserController : Controller
	{
		public const string  NotFoundView     = "../Home/NotFound",
							 LoggedInView     = "LoginRequired",
							 LoggedOutView    = "LogoutRequired",
							 UnauthorizedView = "Unauthorized";

		IWebHostEnvironment _webHostEnvironment;
		private readonly ILogger<UserController> _logger;
		private AppDbContext _context;

		public UserController(IWebHostEnvironment webHostEnvironment, ILogger<UserController> logger, AppDbContext context)
		{
			_webHostEnvironment = webHostEnvironment;
			_logger = logger;
			_context = context;
		}

		[HttpGet]
		public IActionResult Login()
		{
			if (SessionHelper.IsLoggedIn(this))
				return View(LoggedOutView);
			return View();
		}

		[HttpPost]
		public IActionResult PostLogin(IUser info)
		{
			if (SessionHelper.IsLoggedIn(this))
				return View(LoggedOutView);
			else if (!string.IsNullOrEmpty(info.Password) && !Regex.IsMatch(info.Password.ToLower(), "^[a-zA-Z0-9]*$"))
				ModelState.AddModelError("Password", "Password must contain only alphanumeric characters.");

			if (ModelState.GetValidationState("Email") == ModelValidationState.Valid &&
				ModelState.GetValidationState("Password") == ModelValidationState.Valid)
			{
				IUser? user = _context.Users
					.Where(x =>
								x.Email.ToLower() == info.Email.ToLower() &&
								x.Password.ToLower() == IUser.GetPassswordHash(info.Password).ToLower()
						  )
					.Include(x => x.Services)
						.ThenInclude(x => x.Service)
					.Include(x => x.BannedUser)
					.FirstOrDefault();

				if (user != null)
				{
					if (user.BannedUser == null)
					{
						SessionHelper.SetSession(this, user);
						return RedirectToAction("Index");
					}
					else
						ModelState.AddModelError(string.Empty, string.Format("This user is banned for {0}.", user.BannedUser.BanReason));
				}
				else
					ModelState.AddModelError(string.Empty, "Email address or password was incorrect, please try again.");
			}
			return View("Login");
		}

		[HttpGet]
		public IActionResult Register()
		{
			if (SessionHelper.IsLoggedIn(this))
				return View(LoggedOutView);
			return View();
		}

		[HttpPost]
		public IActionResult PostRegister(IUser user, string pwconfirm, IFormFile? ppimg)
		{
			if (SessionHelper.IsLoggedIn(this))
				return View(LoggedOutView);
			else if (!string.IsNullOrEmpty(user.Password) && !Regex.IsMatch(user.Password.ToLower(), "^[a-zA-Z0-9]*$"))
				ModelState.AddModelError("Password", "Password must contain only alphanumeric characters.");
			else if (string.IsNullOrEmpty(pwconfirm) || (!string.IsNullOrEmpty(user.Password) && user.Password != pwconfirm))
				ModelState.AddModelError(string.Empty, "Please confirm your password correctly.");

			if (ModelState.IsValid)
			{
				if (_context.Users.FirstOrDefault(x => x.Email.ToLower() == user.Email.ToLower()) == null)
				{
					user.SetImage(_webHostEnvironment.WebRootPath, ppimg);
					user.HashPassword();

					_context.Users.Add(user);
					_context.SaveChanges();

					SessionHelper.SetSession(this, user);
					return RedirectToAction("Index");
				}
				else
					ModelState.AddModelError(string.Empty, "This email address is already in use.");
			}
			return View("Register");
		}

		[HttpGet]
		public IActionResult Index()
		{
			IUser? user = SessionHelper.GetSession(this);
			if (user == null)
				return RedirectToAction("Login");

			if (user.IsAdmin)
			{
				ViewBag.UserCount = _context.Users.Count();
				ViewBag.ServiceCount = _context.Services.Count();
				ViewBag.RequestCount = _context.ServiceRequests.Count();
				ViewBag.BannedUserCount = _context.BannedUsers.Count();
			}
			return View(user);
		}

		[HttpGet]
		public IActionResult Profile(int? id)
		{
			IUser? user = SessionHelper.GetSession(this);
			if (user == null)
				return View(LoggedInView);

			return View(
				user.IsAdmin && id != null && id > 0
				? _context.Users.FirstOrDefault(x => x.Id == id) //admin user lookup
				: user //normal user profile
				);
		}

		[HttpPost]
		public IActionResult EditProfile(IUser info, IFormFile? ppimg)
		{
			IUser? user = SessionHelper.GetSession(this);
			if (user == null)
				return View(LoggedInView);

			if (
				ModelState.GetValidationState("Name") == ModelValidationState.Valid &&
				ModelState.GetValidationState("BirthDate") == ModelValidationState.Valid
				)
			{
				IUser? target = null;
				if (info.Id > 0 && (info.Id == user.Id || user.IsAdmin))
					target = _context.Users.FirstOrDefault(x => x.Id == info.Id);

				if (target != null)
				{
					target.Edit(info);
					if (ppimg != null)
						target.ReplaceImage(_webHostEnvironment.WebRootPath, ppimg);

					info = target;
					if (info.Id == user.Id)
						SessionHelper.SetSession(this, target);

					_context.SaveChanges();
					ViewBag.Success = true;
				}
				else
					ModelState.AddModelError(string.Empty, "User could not be found.");
			}
			return View("Profile", info);
		}

		[HttpGet]
		public IActionResult DeletePP(int id)
		{
			IUser? user = SessionHelper.GetSession(this);
			if (user == null)
				return View(LoggedInView);

			IUser? target = null;
			if (id != null & id > 0 && (user.Id == id || user.IsAdmin))
				target = _context.Users.FirstOrDefault(x => x.Id == id);

			if (target != null)
			{
				if (target.DeleteImage(_webHostEnvironment.WebRootPath))
				{
					if (id == user.Id)
						SessionHelper.SetSession(this, target);
					_context.SaveChanges();

					ViewBag.Success = true;
				}
				else
					ModelState.AddModelError(string.Empty, "There's no profile picture to be deleted.");
			}
			else
				ModelState.AddModelError(string.Empty, "User could not be found.");

			return View("Profile", target);
		}

		[HttpGet]
		public IActionResult Admin()
		{
			if (!SessionHelper.IsLoggedIn(this, true))
				return View(UnauthorizedView);

			return View("Admin/Index", _context.Users
				.Include(x => x.BannedUser)
				.Include(x => x.Services)
				.ToList());
		}

		[HttpGet]
		public IActionResult SetAdmin(int id, bool to)
		{
			if (!SessionHelper.IsLoggedIn(this, true))
				return View(UnauthorizedView);

			IUser? user = _context.Users.FirstOrDefault(x => x.Id == id);
			if (user != null)
			{
				user.IsAdmin = to;
				_context.SaveChanges();

				return RedirectToAction("Admin");
			}
			return View(NotFoundView);
		}

		[HttpGet]
		public IActionResult Service(int id)
		{
			if (!SessionHelper.IsLoggedIn(this, true))
				return View(UnauthorizedView);

			return View("Service/Index", _context.Users
				.Where(x => x.Id == id)
				.Include(x => x.Services)
					.ThenInclude(x => x.Service)
				.FirstOrDefault());
		}

		[HttpGet]
		public IActionResult AddService(int id)
		{
			if (!SessionHelper.IsLoggedIn(this, true))
				return View(UnauthorizedView);

			IUser? user = _context.Users.FirstOrDefault(x => x.Id == id);
			if (user != null)
				ViewBag.Services = new SelectList(_context.Services, "Id", "Name");

			return View("Service/Add", new UserService
			{
				UserId = id
			});
		}

		[HttpPost]
		public IActionResult PostAddService(UserService service)
		{
			if (!SessionHelper.IsLoggedIn(this, true))
				return View(UnauthorizedView);

			IUser? user = _context.Users.FirstOrDefault(x => x.Id == service.UserId);
			if (user != null)
			{
				if (_context.Services.FirstOrDefault(x => x.Id == service.ServiceId) != null)
				{
					_context.UserServices.Add(service);
					_context.SaveChanges();

					return RedirectToAction("Service", new { id = service.UserId });
				}
				else
					ModelState.AddModelError(string.Empty, "Service could not be found.");
			}
			else
				ModelState.AddModelError(string.Empty, "User could not be found.");
			return View("Service/Add", service);
		}

		[HttpGet]
		public IActionResult DeleteService(int id)
		{
			if (!SessionHelper.IsLoggedIn(this, true))
				return View(UnauthorizedView);

			return View("Service/Delete", _context.UserServices
				.Where(x => x.Id == id)
				.Include(x => x.User)
				.Include(x => x.Service)
				.FirstOrDefault());
		}

		[HttpPost]
		public IActionResult PostDeleteService(int id)
		{
			if (!SessionHelper.IsLoggedIn(this, true))
				return View(UnauthorizedView);

			UserService? service = _context.UserServices.FirstOrDefault(x => x.Id == id);
			if (service != null)
			{
				int userid = service.UserId;

				_context.UserServices.Remove(service);
				_context.SaveChanges();

				return RedirectToAction("Service", new { id = service.UserId });
			}
			else
				ModelState.AddModelError(string.Empty, "Service could not be found.");
			return View("Service/Add", service);
		}

		[HttpGet]
        public IActionResult Logout()
        {
            if (!SessionHelper.IsLoggedIn(this))
                return View(LoggedInView);

			SessionHelper.DeleteSession(this);
            return RedirectToAction("Index", "Home");
        }
	}
}

ServiceProvider/Views/Ban/Add.cshtml
@{
	ViewData["Title"] = "Ban User";
}

@model BannedUser

<h2 class="alert alert-info text-center">Ban User</h2>

<form method="post" class="col-4" asp-controller="Ban" asp-action="PostAdd">

	<div class="form-group">
		<label asp-for="UserId"></label>
		<input type="text" asp-for="UserId" class="form-control" aria-describedby="useridHelp" placeholder="Enter user ID">

		<div class="row">
			<small id="useridHelp" class="form-text text-muted">Enter ID of the user you want to ban.</small>
		</div>
	</div>

	<div class="form-group pt-2">
		<label asp-for="BanReason"></label>
		<input type="text" asp-for="BanReason" class="form-control" aria-describedby="banHelp" placeholder="Enter reason for ban">

		<div class="row">
			<small id="banHelp" class="form-text text-muted">Choose a brief explaination why this user is getting banned.</small>
			<span asp-validation-for="BanReason" class="form-text text-danger"></span>
		</div>
	</div>

	<div asp-validation-summary="ModelOnly" class="form-group text-danger pt-3"></div>

	<div class="mt-2">
		<button type="submit" class="btn btn-primary">Ban</button>
		<a class="btn btn-danger ms-2" asp-controller="Ban" asp-action="Index">Back</a>
	</div>

</form>

ServiceProvider/Views/Ban/Delete.cshtml
@{
	ViewData["Title"] = "Revoke Ban";
}

@model BannedUser?

@if (Model != null)
{
	<h2 class="alert alert-info text-center">Revoke Ban</h2>

	<dt>@Html.DisplayNameFor(x => x.UserId)</dt>
	<dd>@Html.DisplayFor(x => x.UserId)</dd>

	<dt>@Html.DisplayNameFor(x => x.User.Name)</dt>
	<dd>@Html.DisplayFor(x => x.User.Name)</dd>

	<dt>@Html.DisplayNameFor(x => x.User.Email)</dt>
	<dd>@Html.DisplayFor(x => x.User.Email)</dd>

	<dt>@Html.DisplayNameFor(x => x.BanReason)</dt>
	<dd>@Html.DisplayFor(x => x.BanReason)</dd>

	<dt>@Html.DisplayNameFor(x => x.BanTime)</dt>
	<dd>@Html.DisplayFor(x => x.BanTime)</dd>

	<form method="post" asp-controller="Ban" asp-action="PostDelete" asp-route-id="@Model.Id">
		<div class="d-flex pt-1">
			<button type="submit" class="btn btn-danger">Delete</button>
			<a class="btn btn-danger ms-2" asp-controller="Ban" asp-action="Index">Back</a>
		</div>
	</form>
}
else
{
	<h3 class="alert alert-danger text-center">Ban could not be found.</h3>
}

ServiceProvider/Views/Ban/Index.cshtml
@{
	ViewData["Title"] = "Ban Management";
}

@model IEnumerable<BannedUser>

<h2 class="alert alert-info text-center">Ban Management</h2>

<a class="btn btn-info" asp-controller="Ban" asp-action="Add">Ban User</a>
<a class="btn btn-danger" asp-controller="User" asp-action="Index">Back</a>

<table class="table table-hover table-bordered border-secondary table-striped mt-3">
	<thead class="table-info border-secondary">
		<tr>
			<th>@Html.DisplayNameFor(x => x.UserId)</th>
			<th>@Html.DisplayNameFor(x => x.User.Name)</th>
			<th>@Html.DisplayNameFor(x => x.User.Email)</th>
			<th>@Html.DisplayNameFor(x => x.BanReason)</th>
			<th>@Html.DisplayNameFor(x => x.BanTime)</th>
			<th class="text-center" style="width: 5%;">Actions</th>
		</tr>
	</thead>

	<tbody>
		@foreach (var item in Model)
		{
			<tr class="align-middle">
				<td>@item.UserId</td>
				<td>@item.User.Name</td>
				<td>@item.User.Email</td>
				<td>@item.BanReason</td>
				<td>@item.BanTime</td>

				<td>
					<div class="d-flex justify-content-center">
						<a class="btn btn-sm btn-outline-danger" asp-controller="Ban" asp-action="Delete" asp-route-id="@item.Id">
							<svg bootstrap-icon="Trash3" width="18" height="24"></svg>
						</a>
					</div>
				</td>
			</tr>
		}
	</tbody>

	<tfoot>
		<tr>
			<td>Total</td>
			<td colspan="5">@Model.Count() bans</td>
		</tr>
	</tfoot>
</table>