ServiceProvider/Controllers/BanController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ServiceProvider.Database;
using ServiceProvider.Helpers;
using ServiceProvider.Models;

namespace ServiceProvider.Controllers
{
	public class BanController : Controller
	{
		public const string UnauthorizedView = "../User/Unauthorized";

		IWebHostEnvironment _webHostEnvironment;
		private readonly ILogger<BanController> _logger;
		private AppDbContext _context;

		public BanController(IWebHostEnvironment webHostEnvironment, ILogger<BanController> logger, AppDbContext context)
		{
			_webHostEnvironment = webHostEnvironment;
			_logger = logger;
			_context = context;
		}

		[HttpGet]
		public IActionResult Index()
		{
			if (!SessionHelper.IsLoggedIn(this, true))
				return View(UnauthorizedView);

			return View(_context.BannedUsers
				.Include(x => x.User)
				.OrderByDescending(x => x.BanTime)
				.ToList()
				);
		}

		[HttpGet]
		public IActionResult Add(int? id)
		{
			if (!SessionHelper.IsLoggedIn(this, true))
				return View(UnauthorizedView);

			return View(id != null ?
				new BannedUser { UserId = id.Value }
				: null);
		}

		[HttpPost]
		public IActionResult PostAdd(BannedUser ban)
		{
			if (!SessionHelper.IsLoggedIn(this, true))
				return View(UnauthorizedView);

			if (ModelState.IsValid)
			{
				if (_context.Users.FirstOrDefault(x => x.Id == ban.UserId) != null)
				{
					if (_context.BannedUsers.FirstOrDefault(x => x.UserId ==  ban.UserId) == null)
					{
						ban.BanTime = DateTime.Now;

						_context.BannedUsers.Add(ban);
						_context.SaveChanges();

						return RedirectToAction("Index");
					}
					else
						ModelState.AddModelError(string.Empty, "This user is already banned.");
				}
				else
					ModelState.AddModelError(string.Empty, "User could not be found.");
			}
			return View("Add", ban);
		}

		[HttpGet]
		public IActionResult Delete(int id)
		{
			if (!SessionHelper.IsLoggedIn(this, true))
				return View(UnauthorizedView);

			return View(_context.BannedUsers
				.Where(x => x.Id == id)
				.Include(x => x.User)
				.FirstOrDefault()
				);
		}

		[HttpPost]
		public IActionResult PostDelete(int id)
		{
			if (!SessionHelper.IsLoggedIn(this, true))
				return View(UnauthorizedView);

			if (id != null && id > 0)
			{
				BannedUser? ban = _context.BannedUsers.FirstOrDefault(x => x.Id == id);
				if (ban != null)
				{
					_context.BannedUsers.Remove(ban);
					_context.SaveChanges();

					return RedirectToAction("Index");
				}
			}
			return View("Delete", null);
		}
	}
}

ServiceProvider/Controllers/RequestController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.EntityFrameworkCore;
using ServiceProvider.Database;
using ServiceProvider.Helpers;
using ServiceProvider.Models;

namespace ServiceProvider.Controllers
{
	public class RequestController : Controller
	{
		public const string UnauthorizedView = "../User/Unauthorized",
							LoggedInView = "../User/LoginRequired";

		IWebHostEnvironment _webHostEnvironment;
		private readonly ILogger<RequestController> _logger;
		private AppDbContext _context;

		public RequestController(IWebHostEnvironment webHostEnvironment, ILogger<RequestController> logger, AppDbContext context)
		{
			_webHostEnvironment = webHostEnvironment;
			_logger = logger;
			_context = context;
		}

		[HttpGet]
		public IActionResult Index()
		{
			if (!SessionHelper.IsLoggedIn(this, true))
				return View(UnauthorizedView);

			return View(_context.ServiceRequests
				.Include(x => x.User)
				.Include(x => x.Service)
				.ToList()
				);
		}

		[HttpGet]
		public IActionResult View(int id)
		{
			if (!SessionHelper.IsLoggedIn(this, true))
				return View(UnauthorizedView);

			return View(_context.ServiceRequests
				.Where(x => x.Id == id)
				.Include(x => x.User)
				.Include(x => x.Service)
				.FirstOrDefault());
		}

		[HttpGet]
		public IActionResult Add()
		{
			if (!SessionHelper.IsLoggedIn(this))
				return View(LoggedInView);

			ViewBag.Services = new SelectList(_context.Services.ToList(), "Id", "Name");
			return View();
		}

		[HttpPost]
		public IActionResult PostAdd(ServiceRequest request)
		{
			IUser? user = SessionHelper.GetSession(this);
			if (user == null)
				return View(LoggedInView);

			if (
				ModelState.GetValidationState("ServiceId") == ModelValidationState.Valid &&
                ModelState.GetValidationState("About") == ModelValidationState.Valid
				)
			{
				if (_context.Services.FirstOrDefault(x => x.Id == request.ServiceId) != null)
				{
					request.UserId = user.Id;
					request.RequestTime = DateTime.Now;

                    if (request.About != null)
                        request.About = request.About.Replace("\r\n", "\\n").Replace("\n", "\\n").Replace("\t", "\\t");

                    _context.ServiceRequests.Add(request);
					_context.SaveChanges();

					return RedirectToAction("Submitted");
				}
				else
					ModelState.AddModelError(string.Empty, "Service could not be found.");
			}
			return View("Add", request);
		}

		[HttpGet]
		public IActionResult Submitted()
		{
			if (!SessionHelper.IsLoggedIn(this))
				return View(LoggedInView);
			return View();
		}
	}
}

ServiceProvider/Controllers/ServiceController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ServiceProvider.Database;
using ServiceProvider.Helpers;
using ServiceProvider.Models;

namespace ServiceProvider.Controllers
{
    public class ServiceController : Controller
    {
		public const string UnauthorizedView = "../User/Unauthorized";

		IWebHostEnvironment _webHostEnvironment;
		private readonly ILogger<ServiceController> _logger;
		private AppDbContext _context;

		public ServiceController(IWebHostEnvironment webHostEnvironment, ILogger<ServiceController> logger, AppDbContext context)
		{
			_webHostEnvironment = webHostEnvironment;
			_logger = logger;
			_context = context;
		}

		[HttpGet]
		public IActionResult Index()
        {
			if (!SessionHelper.IsLoggedIn(this, true))
				return View(UnauthorizedView);
            return View(_context.Services.ToList());
        }

		[HttpGet]
		public IActionResult Add()
		{
			if (!SessionHelper.IsLoggedIn(this, true))
				return View(UnauthorizedView);
			return View();
		}

		[HttpPost]
		public IActionResult PostAdd(Service service)
		{
			if (!SessionHelper.IsLoggedIn(this, true))
				return View(UnauthorizedView);

			if (ModelState.IsValid)
			{
				_context.Services.Add(service);
				_context.SaveChanges();

				return RedirectToAction("Index");
			}
			return View("Add", service);
		}

		[HttpGet]
		public IActionResult Edit(int id)
		{
			if (!SessionHelper.IsLoggedIn(this, true))
				return View(UnauthorizedView);
			return View(_context.Services.FirstOrDefault(x => x.Id == id));
		}

		[HttpPost]
		public IActionResult PostEdit(Service service)
		{
			if (!SessionHelper.IsLoggedIn(this, true))
				return View(UnauthorizedView);

			if (ModelState.IsValid)
			{
				Service? srv = _context.Services.FirstOrDefault(x => x.Id == service.Id);
				if (srv != null)
				{
					srv.Edit(service);
					_context.SaveChanges();

					return RedirectToAction("Index");
				}
				else
					ModelState.AddModelError(string.Empty, "Service could not be found.");
			}
			return View("Edit", service);
		}

		[HttpGet]
		public IActionResult Delete(int id)
		{
			if (!SessionHelper.IsLoggedIn(this, true))
				return View(UnauthorizedView);
			return View(_context.Services.FirstOrDefault(x => x.Id == id));
		}

		[HttpPost]
		public IActionResult PostDelete(int id)
		{
			if (!SessionHelper.IsLoggedIn(this, true))
				return View(UnauthorizedView);

			Service? srv = _context.Services.FirstOrDefault(x => x.Id == id);
			if (srv != null)
			{
				_context.Services.Remove(srv);
				_context.SaveChanges();

				return RedirectToAction("Index");
			}
			return View("Delete", null);
		}
	}
}

ServiceProvider/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using ServiceProvider.Database;
using ServiceProvider.Models;
using Newtonsoft.Json.Converters;
using ServiceProvider.Helpers;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System.Text.RegularExpressions;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.FileProviders;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceProvider.Controllers
{
	public class UserController : Controller
	{
		public const string  NotFoundView     = "../Home/NotFound",
							 LoggedInView     = "LoginRequired",
							 LoggedOutView    = "LogoutRequired",
							 UnauthorizedView = "Unauthorized";

		IWebHostEnvironment _webHostEnvironment;
		private readonly ILogger<UserController> _logger;
		private AppDbContext _context;

		public UserController(IWebHostEnvironment webHostEnvironment, ILogger<UserController> logger, AppDbContext context)
		{
			_webHostEnvironment = webHostEnvironment;
			_logger = logger;
			_context = context;
		}

		[HttpGet]
		public IActionResult Login()
		{
			if (SessionHelper.IsLoggedIn(this))
				return View(LoggedOutView);
			return View();
		}

		[HttpPost]
		public IActionResult PostLogin(IUser info)
		{
			if (SessionHelper.IsLoggedIn(this))
				return View(LoggedOutView);
			else if (!string.IsNullOrEmpty(info.Password) && !Regex.IsMatch(info.Password.ToLower(), "^[a-zA-Z0-9]*$"))
				ModelState.AddModelError("Password", "Password must contain only alphanumeric characters.");

			if (ModelState.GetValidationState("Email") == ModelValidationState.Valid &&
				ModelState.GetValidationState("Password") == ModelValidationState.Valid)
			{
				IUser? user = _context.Users
					.Where(x =>
								x.Email.ToLower() == info.Email.ToLower() &&
								x.Password.ToLower() == IUser.GetPassswordHash(info.Password).ToLower()
						  )
					.Include(x => x.Services)
						.ThenInclude(x => x.Service)
					.Include(x => x.BannedUser)
					.FirstOrDefault();

				if (user != null)
				{
					if (user.BannedUser == null)
					{
						SessionHelper.SetSession(this, user);
						return RedirectToAction("Index");
					}
					else
						ModelState.AddModelError(string.Empty, string.Format("This user is banned for {0}.", user.BannedUser.BanReason));
				}
				else
					ModelState.AddModelError(string.Empty, "Email address or password was incorrect, please try again.");
			}
			return View("Login");
		}

		[HttpGet]
		public IActionResult Register()
		{
			if (SessionHelper.IsLoggedIn(this))
				return View(LoggedOutView);
			return View();
		}

		[HttpPost]
		public IActionResult PostRegister(IUser user, string pwconfirm, IFormFile? ppimg)
		{
			if (SessionHelper.IsLoggedIn(this))
				return View(LoggedOutView);
			else if (!string.IsNullOrEmpty(user.Password) && !Regex.IsMatch(user.Password.ToLower(), "^[a-zA-Z0-9]*$"))
				ModelState.AddModelError("Password", "Password must contain only alphanumeric characters.");
			else if (string.IsNullOrEmpty(pwconfirm) || (!string.IsNullOrEmpty(user.Password) && user.Password != pwconfirm))
				ModelState.AddModelError(string.Empty, "Please confirm your password correctly.");

			if (ModelState.IsValid)
			{
				if (_context.Users.FirstOrDefault(x => x.Email.ToLower() == user.Email.ToLower()) == null)
				{
					user.SetImage(_webHostEnvironment.WebRootPath, ppimg);
					user.HashPassword();

					_context.Users.Add(user);
					_context.SaveChanges();

					SessionHelper.SetSession(this, user);
					return RedirectToAction("Index");
				}
				else
					ModelState.AddModelError(string.Empty, "This email address is already in use.");
			}
			return View("Register");
		}

		[HttpGet]
		public IActionResult Index()
		{
			IUser? user = SessionHelper.GetSession(this);
			if (user == null)
				return RedirectToAction("Login");

			if (user.IsAdmin)
			{
				ViewBag.UserCount = _context.Users.Count();
				ViewBag.ServiceCount = _context.Services.Count();
				ViewBag.RequestCount = _context.ServiceRequests.Count();
				ViewBag.BannedUserCount = _context.BannedUsers.Count();
			}
			return View(user);
		}

		[HttpGet]
		public IActionResult Profile(int? id)
		{
			IUser? user = SessionHelper.GetSession(this);
			if (user == null)
				return View(LoggedInView);

			return View(
				user.IsAdmin && id != null && id > 0
				? _context.Users.FirstOrDefault(x => x.Id == id) //admin user lookup
				: user //normal user profile
				);
		}

		[HttpPost]
		public IActionResult EditProfile(IUser info, IFormFile? ppimg)
		{
			IUser? user = SessionHelper.GetSession(this);
			if (user == null)
				return View(LoggedInView);

			if (
				ModelState.GetValidationState("Name") == ModelValidationState.Valid &&
				ModelState.GetValidationState("BirthDate") == ModelValidationState.Valid
				)
			{
				IUser? target = null;
				if (info.Id > 0 && (info.Id == user.Id || user.IsAdmin))
					target = _context.Users.FirstOrDefault(x => x.Id == info.Id);

				if (target != null)
				{
					target.Edit(info);
					if (ppimg != null)
						target.ReplaceImage(_webHostEnvironment.WebRootPath, ppimg);

					info = target;
					if (info.Id == user.Id)
						SessionHelper.SetSession(this, target);

					_context.SaveChanges();
					ViewBag.Success = true;
				}
				else
					ModelState.AddModelError(string.Empty, "User could not be found.");
			}
			return View("Profile", info);
		}

		[HttpGet]
		public IActionResult DeletePP(int id)
		{
			IUser? user = SessionHelper.GetSession(this);
			if (user == null)
				return View(LoggedInView);

			IUser? target = null;
			if (id != null & id > 0 && (user.Id == id || user.IsAdmin))
				target = _context.Users.FirstOrDefault(x => x.Id == id);

			if (target != null)
			{
				if (target.DeleteImage(_webHostEnvironment.WebRootPath))
				{
					if (id == user.Id)
						SessionHelper.SetSession(this, target);
					_context.SaveChanges();

					ViewBag.Success = true;
				}
				else
					ModelState.AddModelError(string.Empty, "There's no profile picture to be deleted.");
			}
			else
				ModelState.AddModelError(string.Empty, "User could not be found.");

			return View("Profile", target);
		}

		[HttpGet]
		public IActionResult Admin()
		{
			if (!SessionHelper.IsLoggedIn(this, true))
				return View(UnauthorizedView);

			return View("Admin/Index", _context.Users
				.Include(x => x.BannedUser)
				.Include(x => x.Services)
				.ToList());
		}

		[HttpGet]
		public IActionResult SetAdmin(int id, bool to)
		{
			if (!SessionHelper.IsLoggedIn(this, true))
				return View(UnauthorizedView);

			IUser? user = _context.Users.FirstOrDefault(x => x.Id == id);
			if (user != null)
			{
				user.IsAdmin = to;
				_context.SaveChanges();

				return RedirectToAction("Admin");
			}
			return View(NotFoundView);
		}

		[HttpGet]
		public IActionResult Service(int id)
		{
			if (!SessionHelper.IsLoggedIn(this, true))
				return View(UnauthorizedView);

			return View("Service/Index", _context.Users
				.Where(x => x.Id == id)
				.Include(x => x.Services)
					.ThenInclude(x => x.Service)
				.FirstOrDefault());
		}

		[HttpGet]
		public IActionResult AddService(int id)
		{
			if (!SessionHelper.IsLoggedIn(this, true))
				return View(UnauthorizedView);

			IUser? user = _context.Users.FirstOrDefault(x => x.Id == id);
			if (user != null)
				ViewBag.Services = new SelectList(_context.Services, "Id", "Name");

			return View("Service/Add", new UserService
			{
				UserId = id
			});
		}

		[HttpPost]
		public IActionResult PostAddService(UserService service)
		{
			if (!SessionHelper.IsLoggedIn(this, true))
				return View(UnauthorizedView);

			IUser? user = _context.Users.FirstOrDefault(x => x.Id == service.UserId);
			if (user != null)
			{
				if (_context.Services.FirstOrDefault(x => x.Id == service.ServiceId) != null)
				{
					_context.UserServices.Add(service);
					_context.SaveChanges();

					return RedirectToAction("Service", new { id = service.UserId });
				}
				else
					ModelState.AddModelError(string.Empty, "Service could not be found.");
			}
			else
				ModelState.AddModelError(string.Empty, "User could not be found.");
			return View("Service/Add", service);
		}

		[HttpGet]
		public IActionResult DeleteService(int id)
		{
			if (!SessionHelper.IsLoggedIn(this, true))
				return View(UnauthorizedView);

			return View("Service/Delete", _context.UserServices
				.Where(x => x.Id == id)
				.Include(x => x.User)
				.Include(x => x.Service)
				.FirstOrDefault());
		}

		[HttpPost]
		public IActionResult PostDeleteService(int id)
		{
			if (!SessionHelper.IsLoggedIn(this, true))
				return View(UnauthorizedView);

			UserService? service = _context.UserServices.FirstOrDefault(x => x.Id == id);
			if (service != null)
			{
				int userid = service.UserId;

				_context.UserServices.Remove(service);
				_context.SaveChanges();

				return RedirectToAction("Service", new { id = service.UserId });
			}
			else
				ModelState.AddModelError(string.Empty, "Service could not be found.");
			return View("Service/Add", service);
		}

		[HttpGet]
        public IActionResult Logout()
        {
            if (!SessionHelper.IsLoggedIn(this))
                return View(LoggedInView);

			SessionHelper.DeleteSession(this);
            return RedirectToAction("Index", "Home");
        }
	}
}

ServiceProvider/Views/User/Index.cshtml
@model IUser

@{
	ViewData["Title"] = string.Format("{0} Panel", !Model.IsAdmin ? "User" : "Admin");
}

@if (Model != null)
{
	@if (Model.IsAdmin)
	{
		<ul class="list-group col-3">
			<li class="list-group-item list-group-item-action active">
				Actions
			</li>

			<a class="list-group-item list-group-item-action d-flex justify-content-between align-items-center" asp-controller="User" asp-action="Admin">
				Users
				<span class="badge bg-primary rounded-pill user-select-none">@ViewBag.UserCount</span>
			</a>

			<a class="list-group-item list-group-item-action d-flex justify-content-between align-items-center" asp-controller="Service">
				Services
				<span class="badge bg-primary rounded-pill user-select-none">@ViewBag.ServiceCount</span>
			</a>

			<a class="list-group-item list-group-item-action d-flex justify-content-between align-items-center" asp-controller="Request">
				Requests
				<span class="badge bg-primary rounded-pill user-select-none">@ViewBag.RequestCount</span>
			</a>

			<a class="list-group-item list-group-item-action d-flex justify-content-between align-items-center" asp-controller="Ban">
				Bans
				<span class="badge bg-primary rounded-pill user-select-none">@ViewBag.BannedUserCount</span>
			</a>
		</ul>
	}
	else
	{
		<ul class="list-group col-3">
			<li class="list-group-item list-group-item-action active">
				Actions
			</li>

			<a class="list-group-item list-group-item-action d-flex justify-content-between align-items-center" asp-controller="Request" asp-action="Add">
				Request Service
			</a>
		</ul>
	}
}
else
{
	<h2 class="alert alert-danger text-center">Unauthorized access to user panel.</h2>
}

ServiceProvider/Views/User/Login.cshtml
@{
	ViewData["Title"] = "Login";
}

@model IUser

<h2 class="alert alert-info text-center">User Login</h2>

<form method="post" class="col-4" asp-controller="User" asp-action="PostLogin">

	<div class="form-group">
		<label asp-for="Email"></label>
		<input type="email" asp-for="Email" class="form-control" aria-describedby="emailHelp" placeholder="Enter email">
		
		<div class="row">
			<small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
			<span asp-validation-for="Email" class="form-text text-danger"></span>
		</div>
	</div>

	<div class="form-group pt-2">
		<label>Password</label>
		<input type="password" asp-for="Password" class="form-control" aria-describedby="passwordHelp" placeholder="••••••••••">

		<div class="row">
			<small id="passwordHelp" class="form-text text-muted">Pick a strong password and don't share it with others.</small>
			<span asp-validation-for="Password" class="form-text text-danger"></span>
		</div>
	</div>

	<div asp-validation-summary="ModelOnly" class="form-group text-danger pt-3"></div>

	<div class="mt-2">
		<button type="submit" class="btn btn-primary">Login</button>
		<a class="btn btn-success ms-1" asp-controller="User" asp-action="Register">Register</a>
	</div>

</form>

ServiceProvider/Views/User/LoginRequired.cshtml
@{
	ViewData["Title"] = "Login Required";
}

<h3 class="alert alert-danger text-center">You must log in to see this page.</h3>

ServiceProvider/Views/User/LogoutRequired.cshtml
@{
	ViewData["Title"] = "Logout Required";
}

<h3 class="alert alert-danger text-center">You must log out to see this page.</h3>

ServiceProvider/Views/User/Profile.cshtml
@{
	ViewData["Title"] = "User Profile Overview";
}

@model IUser

@if (Model != null)
{
	<h2 class="alert alert-info text-center">User Profile</h2>

	<form method="post" class="col-4" asp-controller="User" asp-action="EditProfile" asp-route-id="@Model.Id" enctype="multipart/form-data">

		<div class="form-group pt-2">
			<label asp-for="Name"></label>
			<input type="text" asp-for="Name" class="form-control" aria-describedby="nameHelp" placeholder="Your name">

			<div class="row">
				<small id="nameHelp" class="form-text text-muted">Can be your real name or username.</small>
				<span asp-validation-for="Name" class="form-text text-danger"></span>
			</div>
		</div>

		<div class="form-group pt-2">
			<label asp-for="BirthDate"></label>
			<input type="date" asp-for="BirthDate" class="form-control" aria-describedby="dobHelp">

			<div class="row">
				<small id="dobHelp" class="form-text text-muted">Enter your date of birth.</small>
				<span asp-validation-for="BirthDate" class="form-text text-danger"></span>
			</div>
		</div>

		<div class="form-group pt-2">
			<label asp-for="ProfilePicture"></label>
			<input type="file" class="form-control" accept=".png,.jpg" onchange="SetProfilePicture()" name="ppimg" id="ppimg" aria-describedby="pictureHelp">

			<div class="row">
				<small id="pictureHelp" class="form-text text-muted">[Optional] Choose a profile picture that represent you.</small>
			</div>

			<div class="col-4 pt-2 pb-1">
				<img asp-controller="Home" src="~/@Model.ProfilePictureImage" id="ppic" style="max-height: 100px;" />
			</div>
		</div>

		@if (ViewBag.Success != null && ViewBag.Success)
		{
			<p class="form-group ex text-success pt-4">Changes have been submitted successfully.</p>
		}
		else
		{
			<div asp-validation-summary="ModelOnly" class="form-group text-danger pt-4"></div>
		}

		<div class="mt-2">
			<button type="submit" class="btn btn-primary">Submit Changes</button>
			<a class="btn btn-danger ms-1 @Model.ProfilePictureState" asp-controller="User" asp-action="DeletePP" asp-route-id="@Model.Id">Delete Profile Picture</a>
		</div>
	</form>
}
else
{
	<h3 class="alert alert-danger text-center">User could not be found.</h3>
}

@section Scripts
	{
	<script>
		function SetProfilePicture() {
			document.getElementById('ppic').src = window.URL.createObjectURL(document.getElementById('ppimg').files[0]);
		}
	</script>
}

ServiceProvider/Views/User/Register.cshtml
@{
	ViewData["Title"] = "Registration";
}

@model IUser

<h2 class="alert alert-info text-center">User Registration</h2>

<form method="post" class="col-4" asp-controller="User" asp-action="PostRegister" enctype="multipart/form-data">

	<div class="form-group">
		<label asp-for="Name"></label>
		<input type="text" asp-for="Name" class="form-control" aria-describedby="nameHelp" placeholder="Your name">

		<div class="row">
			<small id="nameHelp" class="form-text text-muted">Can be your real name or username.</small>
			<span asp-validation-for="Name" class="form-text text-danger"></span>
		</div>
	</div>

	<div class="form-group pt-2">
		<label asp-for="Email"></label>
		<input type="email" asp-for="Email" class="form-control" aria-describedby="emailHelp" placeholder="Enter email">

		<div class="row">
			<small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
			<span asp-validation-for="Email" class="form-text text-danger"></span>
		</div>
	</div>

	<div class="form-group pt-2">
		<label>Password</label>
		<input type="password" asp-for="Password" class="form-control" aria-describedby="passwordHelp" placeholder="••••••••••">

		<div class="row">
			<small id="passwordHelp" class="form-text text-muted">Pick a strong password and don't share it with others.</small>
			<span asp-validation-for="Password" class="form-text text-danger"></span>
		</div>
	</div>

	<div class="form-group pt-2">
		<label>Confirm Password</label>
		<input type="password" class="form-control" name="pwconfirm" id="pwconfirm" aria-describedby="passwordcHelp" placeholder="••••••••••">

		<div class="row">
			<small id="passwordcHelp" class="form-text text-muted">Type your password once again to confirm.</small>
		</div>
	</div>

	<div class="form-group pt-2">
		<label asp-for="BirthDate"></label>
		<input type="date" asp-for="BirthDate" class="form-control" aria-describedby="dobHelp">

		<div class="row">
			<small id="dobHelp" class="form-text text-muted">Enter your date of birth.</small>
			<span asp-validation-for="BirthDate" class="form-text text-danger"></span>
		</div>
	</div>

	<div class="form-group pt-2">
		<label asp-for="ProfilePicture"></label>
		<input type="file" class="form-control" accept=".png,.jpg" onchange="SetProfilePicture()" name="ppimg" id="ppimg" aria-describedby="pictureHelp">

		<div class="row">
			<small id="pictureHelp" class="form-text text-muted">[Optional] Choose a profile picture that represent you.</small>
		</div>

		<div class="col-4 pt-2 pb-1">
			<img src="" id="ppic" style="max-height: 100px;" />
		</div>
	</div>

	<div asp-validation-summary="ModelOnly" class="form-group text-danger pt-3"></div>

	<div class="mt-2">
		<button type="submit" class="btn btn-primary">Register</button>
		<a class="btn btn-success ms-1" asp-controller="User" asp-action="Login">Login</a>
	</div>

</form>

@section Scripts
{
	<script>
		function SetProfilePicture()
		{
			document.getElementById('ppic').src = window.URL.createObjectURL(document.getElementById('ppimg').files[0]);
		}
	</script>
}

ServiceProvider/Views/User/Unauthorized.cshtml
@{
	ViewData["Title"] = "404 - Unauthorized";
}

<h3 class="alert alert-danger text-center">Unauthorized access to this page.</h3>